### PR TITLE
ACS-3358 Remove demo tests.

### PR DESCRIPTION
**Pull request by tpage-alfresco**
These were only intended to demonstrate how to use the TAS library.

Also make tests run against all branches.

### CODE REVIEW

**Comment by KikoUK** [comment]
Why are we removing demo tests, aren't they added as an example?

**Comment by tpage-alfresco** [comment]
There's no need for example tests now, since we have an entire suite of "real" tests to use as examples.

Additionally these tests complicate the build for this project, since we need to exclude them.

**Comment by tpage-alfresco** [comment]
Basically I wanted to add more unit tests and found that they wouldn't get run.  By deleting these demo tests and updating the build then we can run all tests by default.

**Comment by KikoUK** [comment]
> There's no need for example tests now, since we have an entire suite of "real" tests to use as examples.
> 
> Additionally these tests complicate the build for this project, since we need to exclude them.

Are the "real" tests in the alfresco-tas-restapi project?

Can the example test be excluded from the build? (possibly by removing the @Test)

**Comment by tpage-alfresco** [comment]
The "real" tests are in various other projects - e.g. the community repo project. On a related topic we should move this project to be inside that project - see https://alfresco.atlassian.net/wiki/spaces/TECH/pages/983761180/RFC+-+Release+Improvements which is open for review comments at the moment.

> Can the example test be excluded from the build? (possibly by removing the @test)

I don't think it's a good idea to try to maintain these tests if they're not being executed. They might be out of date already and no one would know.

**Review by KikoUK — APPROVED** [review]

**Pull request merged**
